Repository TeamPINGLE/PINGLE-SERVER, pull requests merged in 2024-03, with the labels that each got.

#120 회원 탈퇴 시 팀 미탈퇴 이슈 수정
  src/main/java/org/pingle/pingleserver/service/UserService.java
Labels: bug, api

#122 [feat] dev 서버용 토큰 발행 api 제작
  src/main/java/org/pingle/pingleserver/controller/TestController.java
Labels: api, for test

#126 [fix] 번개참여 취소 에러메시지 변경
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/service/UserMeetingService.java
Labels: fix

#128 [fix] 외부 api 호출시 에러처리
  src/main/java/org/pingle/pingleserver/utils/NaverUtil.java
Labels: api, fix
