Repository TeamPINGLE/PINGLE-SERVER, pull requests merged in 2024-01, with the labels that each got.

#10 [feat] 엔티티 생성
  src/main/java/org/pingle/pingleserver/config/JpaAuditingConfig.java
  src/main/java/org/pingle/pingleserver/domain/Address.java
  src/main/java/org/pingle/pingleserver/domain/BaseTimeEntity.java
  src/main/java/org/pingle/pingleserver/domain/Meeting.java
  src/main/java/org/pingle/pingleserver/domain/Pin.java
  src/main/java/org/pingle/pingleserver/domain/Point.java
  src/main/java/org/pingle/pingleserver/domain/Team.java
  src/main/java/org/pingle/pingleserver/domain/User.java
  src/main/java/org/pingle/pingleserver/domain/UserMeeting.java
  src/main/java/org/pingle/pingleserver/domain/UserTeam.java
  src/main/java/org/pingle/pingleserver/domain/enums/MCategory.java
  src/main/java/org/pingle/pingleserver/domain/enums/MRole.java
  src/main/java/org/pingle/pingleserver/domain/enums/TKeyword.java
  src/main/java/org/pingle/pingleserver/domain/enums/TRole.java
  src/main/java/org/pingle/pingleserver/repository/MeetingRepository.java
  src/main/java/org/pingle/pingleserver/repository/PinRepository.java
  src/main/java/org/pingle/pingleserver/repository/TeamRepository.java
  src/main/java/org/pingle/pingleserver/repository/UserMeetingRepository.java
  src/main/java/org/pingle/pingleserver/repository/UserRepository.java
  src/main/java/org/pingle/pingleserver/repository/UserTeamRepository.java
  src/main/java/org/pingle/pingleserver/service/MeetingService.java
  src/main/java/org/pingle/pingleserver/service/PinService.java
  src/main/java/org/pingle/pingleserver/service/TeamService.java
  src/main/java/org/pingle/pingleserver/service/UserMeetingService.java
  src/main/java/org/pingle/pingleserver/service/UserService.java
  src/main/java/org/pingle/pingleserver/service/UserTeamService.java
  src/main/resources/application.yml
Labels: db

#12 [feat] 소셜 로그인 + JWT 구현
  build.gradle
  src/main/java/org/pingle/pingleserver/PingleserverApplication.java
  src/main/java/org/pingle/pingleserver/annotation/UserId.java
  src/main/java/org/pingle/pingleserver/config/FeignClientConfig.java
  src/main/java/org/pingle/pingleserver/config/WebMVCConfig.java
  src/main/java/org/pingle/pingleserver/constant/Constants.java
  src/main/java/org/pingle/pingleserver/controller/AuthController.java
  src/main/java/org/pingle/pingleserver/controller/TestController.java
  src/main/java/org/pingle/pingleserver/domain/User.java
  src/main/java/org/pingle/pingleserver/domain/enums/Provider.java
  src/main/java/org/pingle/pingleserver/domain/enums/URole.java
  src/main/java/org/pingle/pingleserver/dto/request/LoginRequest.java
  src/main/java/org/pingle/pingleserver/dto/response/JwtTokenResponse.java
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/exception/GlobalExceptionHandler.java
  src/main/java/org/pingle/pingleserver/interceptor/pre/UserIdArgumentResolver.java
  src/main/java/org/pingle/pingleserver/oauth/client/AppleFeignClient.java
  src/main/java/org/pingle/pingleserver/oauth/client/KakaoFeignClient.java
  src/main/java/org/pingle/pingleserver/oauth/dto/ApplePublicKey.java
  src/main/java/org/pingle/pingleserver/oauth/dto/ApplePublicKeys.java
  src/main/java/org/pingle/pingleserver/oauth/dto/KakaoAccount.java
  src/main/java/org/pingle/pingleserver/oauth/dto/KakaoUserDto.java
  src/main/java/org/pingle/pingleserver/oauth/dto/KakaoUserProfile.java
  src/main/java/org/pingle/pingleserver/oauth/dto/SocialInfoDto.java
  src/main/java/org/pingle/pingleserver/oauth/service/AppleLoginService.java
  src/main/java/org/pingle/pingleserver/oauth/service/KakaoLoginService.java
  src/main/java/org/pingle/pingleserver/oauth/verify/AppleJwtParser.java
  src/main/java/org/pingle/pingleserver/oauth/verify/PublicKeyGenerator.java
  src/main/java/org/pingle/pingleserver/repository/UserRepository.java
  src/main/java/org/pingle/pingleserver/security/config/SecurityConfig.java
  src/main/java/org/pingle/pingleserver/security/filter/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/pingle/pingleserver/security/filter/JwtAuthenticationFilter.java
  src/main/java/org/pingle/pingleserver/security/info/UserAuthentication.java
  src/main/java/org/pingle/pingleserver/service/AuthService.java
  src/main/java/org/pingle/pingleserver/utils/JwtUtil.java
  src/main/resources/application.yml
Labels: api

#16 [fix] 배포 수정용 Security 설정 변경
  src/main/java/org/pingle/pingleserver/security/config/SecurityConfig.java
Labels: bug

#18 feat] profile 분리를 위한 yml 파일 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  src/main/resources/application.yml
Labels: docs

#13 [feat] 장소검색 api 생성
  src/main/java/org/pingle/pingleserver/controller/OpenApiController.java
  src/main/java/org/pingle/pingleserver/dto/reponse/LocationResponse.java
  src/main/java/org/pingle/pingleserver/dto/reponse/NaverLocationResponse.java
  src/main/java/org/pingle/pingleserver/dto/request/NaverLocationRequest.java
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/utils/naversearchutil/NaverUtil.java
Labels: api

#29 [refac] yml, github template refac
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/org/pingle/pingleserver/utils/naversearchutil/NaverUtil.java
Labels: docs

#33 [feat] 번개 참여 및 취소 api 생성
  src/main/java/org/pingle/pingleserver/controller/MeetingController.java
  src/main/java/org/pingle/pingleserver/domain/UserMeeting.java
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/dto/type/SuccessMessage.java
  src/main/java/org/pingle/pingleserver/repository/UserMeetingRepository.java
  src/main/java/org/pingle/pingleserver/service/MeetingService.java
  src/main/java/org/pingle/pingleserver/service/UserMeetingService.java
Labels: api

#20 [feat] Auth 관련 API 생성
  src/main/java/org/pingle/pingleserver/controller/AuthController.java
  src/main/java/org/pingle/pingleserver/dto/request/ReissueRequest.java
  src/main/java/org/pingle/pingleserver/dto/type/SuccessMessage.java
  src/main/java/org/pingle/pingleserver/repository/UserRepository.java
  src/main/java/org/pingle/pingleserver/service/AuthService.java
Labels: api

#27 [feat] 단체 가입 flow 관련 API 작업
  src/main/java/org/pingle/pingleserver/controller/TeamController.java
  src/main/java/org/pingle/pingleserver/domain/UserTeam.java
  src/main/java/org/pingle/pingleserver/dto/request/TeamRegisterRequest.java
  src/main/java/org/pingle/pingleserver/dto/response/SelectedTeamResponse.java
  src/main/java/org/pingle/pingleserver/dto/response/TeamDetailDto.java
  src/main/java/org/pingle/pingleserver/dto/response/TeamRegistResponse.java
  src/main/java/org/pingle/pingleserver/dto/response/TeamSearchResultResponse.java
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/repository/TeamRepository.java
  src/main/java/org/pingle/pingleserver/repository/UserTeamRepository.java
  src/main/java/org/pingle/pingleserver/service/TeamService.java
  src/main/java/org/pingle/pingleserver/utils/CustomSearchUtil.java
Labels: api

#25 [feat] 번개 생성 api
  src/main/java/org/pingle/pingleserver/annotation/GUserId.java
  src/main/java/org/pingle/pingleserver/config/WebMVCConfig.java
  src/main/java/org/pingle/pingleserver/controller/MeetingController.java
  src/main/java/org/pingle/pingleserver/domain/Meeting.java
  src/main/java/org/pingle/pingleserver/domain/Pin.java
  src/main/java/org/pingle/pingleserver/domain/UserMeeting.java
  src/main/java/org/pingle/pingleserver/dto/request/MeetingRequest.java
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/interceptor/pre/GUserIdArgumentResolver.java
  src/main/java/org/pingle/pingleserver/repository/PinRepository.java
  src/main/java/org/pingle/pingleserver/repository/UserMeetingRepository.java
  src/main/java/org/pingle/pingleserver/repository/UserTeamRepository.java
  src/main/java/org/pingle/pingleserver/service/MeetingService.java
  src/main/java/org/pingle/pingleserver/service/PinService.java
  src/main/java/org/pingle/pingleserver/service/UserMeetingService.java
Labels: api

#31 [feat] 핀 관련 api 생성
  src/main/java/org/pingle/pingleserver/controller/PinController.java
  src/main/java/org/pingle/pingleserver/domain/Pin.java
  src/main/java/org/pingle/pingleserver/domain/enums/MCategory.java
  src/main/java/org/pingle/pingleserver/dto/reponse/MeetingResponse.java
  src/main/java/org/pingle/pingleserver/dto/reponse/PinResponse.java
  src/main/java/org/pingle/pingleserver/repository/PinRepository.java
  src/main/java/org/pingle/pingleserver/repository/UserMeetingRepository.java
  src/main/java/org/pingle/pingleserver/service/PinService.java
Labels: api

#30 [feat] 유저 관련 API 작업
  src/main/java/org/pingle/pingleserver/controller/UserController.java
  src/main/java/org/pingle/pingleserver/dto/response/UserInfoResponse.java
  src/main/java/org/pingle/pingleserver/repository/UserRepository.java
  src/main/java/org/pingle/pingleserver/service/UserService.java
Labels: api

#36 [feat] 클라 테스트를 위한 유저 서버 토큰 반환 API
  src/main/java/org/pingle/pingleserver/controller/TestController.java
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/service/AuthService.java
  src/main/java/org/pingle/pingleserver/service/UserService.java
Labels: for test

#40 [feat] 로그인한 유저 정보 불러오기 API에 단체 추가
  src/main/java/org/pingle/pingleserver/domain/User.java
  src/main/java/org/pingle/pingleserver/dto/response/SimpleGroupInfo.java
  src/main/java/org/pingle/pingleserver/dto/response/UserInfoResponse.java
Labels: api

#42 [fix] reissue 만료 토큰 문제 해결
  src/main/java/org/pingle/pingleserver/security/config/SecurityConfig.java
  src/main/java/org/pingle/pingleserver/service/AuthService.java
Labels: fix

#43 [refac] 코드리뷰 적용 및 패키지 구조 변경
  src/main/java/org/pingle/pingleserver/controller/OpenApiController.java
  src/main/java/org/pingle/pingleserver/controller/TestController.java
  src/main/java/org/pingle/pingleserver/dto/common/ApiResponse.java
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/exception/CustomException.java
  src/main/java/org/pingle/pingleserver/exception/GlobalExceptionHandler.java
  src/main/java/org/pingle/pingleserver/interceptor/pre/GUserIdArgumentResolver.java
  src/main/java/org/pingle/pingleserver/interceptor/pre/UserIdArgumentResolver.java
  src/main/java/org/pingle/pingleserver/oauth/dto/ApplePublicKeys.java
  src/main/java/org/pingle/pingleserver/oauth/verify/AppleJwtParser.java
  src/main/java/org/pingle/pingleserver/oauth/verify/PublicKeyGenerator.java
  src/main/java/org/pingle/pingleserver/repository/TeamRepository.java
  src/main/java/org/pingle/pingleserver/repository/UserRepository.java
  src/main/java/org/pingle/pingleserver/service/AuthService.java
  src/main/java/org/pingle/pingleserver/service/PinService.java
  src/main/java/org/pingle/pingleserver/service/TeamService.java
  src/main/java/org/pingle/pingleserver/service/UserMeetingService.java
  src/main/java/org/pingle/pingleserver/service/UserService.java
  src/main/java/org/pingle/pingleserver/utils/JwtUtil.java
  src/main/java/org/pingle/pingleserver/utils/NaverUtil.java
Labels: refactor

#45 [refac] 코드리뷰 리팩토링
  src/main/java/org/pingle/pingleserver/controller/MeetingController.java
  src/main/java/org/pingle/pingleserver/controller/PinController.java
  src/main/java/org/pingle/pingleserver/controller/TeamController.java
  src/main/java/org/pingle/pingleserver/dto/response/TeamRegistResponse.java
  src/main/java/org/pingle/pingleserver/dto/response/TeamRegisterResponse.java
  src/main/java/org/pingle/pingleserver/service/PinService.java
  src/main/java/org/pingle/pingleserver/service/TeamService.java
Labels: refactor

#49 [feat] http 상태코드 일치, Request 헤더명 변경
  src/main/java/org/pingle/pingleserver/constant/Constants.java
  src/main/java/org/pingle/pingleserver/controller/AuthController.java
  src/main/java/org/pingle/pingleserver/controller/MeetingController.java
  src/main/java/org/pingle/pingleserver/interceptor/post/PingleResponseAdvice.java
  src/main/java/org/pingle/pingleserver/interceptor/pre/GUserIdArgumentResolver.java
Labels: fix

#54 [fix] refreshToken 설계 오류
  src/main/java/org/pingle/pingleserver/controller/AuthController.java
  src/main/java/org/pingle/pingleserver/controller/TestController.java
  src/main/java/org/pingle/pingleserver/dto/request/ReissueRequest.java
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/security/filter/JwtAuthenticationFilter.java
  src/main/java/org/pingle/pingleserver/service/AuthService.java
Labels: fix

#59 [fix] get pins, get meetings detail api 수정
  src/main/java/org/pingle/pingleserver/controller/PinController.java
  src/main/java/org/pingle/pingleserver/dto/reponse/PinResponse.java
  src/main/java/org/pingle/pingleserver/dto/request/MeetingRequest.java
  src/main/java/org/pingle/pingleserver/service/PinService.java
Labels: bug

#63 [fix] get meetings details api 수정
  src/main/java/org/pingle/pingleserver/dto/reponse/MeetingResponse.java
  src/main/java/org/pingle/pingleserver/repository/UserMeetingRepository.java
  src/main/java/org/pingle/pingleserver/service/PinService.java
  src/main/java/org/pingle/pingleserver/service/UserMeetingService.java
Labels: bug

#66 [fix] get meetings details api 수정
  src/main/java/org/pingle/pingleserver/service/PinService.java
Labels: bug

#74 [fix] reissue 에러 세분화
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/service/AuthService.java
  src/main/java/org/pingle/pingleserver/utils/JwtUtil.java
Labels: fix

#78 [feat] 미팅 참여자 명단 api 생성
  src/main/java/org/pingle/pingleserver/controller/MeetingController.java
  src/main/java/org/pingle/pingleserver/domain/UserMeeting.java
  src/main/java/org/pingle/pingleserver/dto/request/MeetingRequest.java
  src/main/java/org/pingle/pingleserver/dto/response/ParticipantsResponse.java
  src/main/java/org/pingle/pingleserver/service/MeetingService.java
Labels: api

#81 [fix] 미팅 생성 api, get meetings api 수정
  src/main/java/org/pingle/pingleserver/controller/PinController.java
  src/main/java/org/pingle/pingleserver/domain/Pin.java
  src/main/java/org/pingle/pingleserver/dto/reponse/MeetingResponse.java
  src/main/java/org/pingle/pingleserver/dto/reponse/PinResponse.java
  src/main/java/org/pingle/pingleserver/dto/request/MeetingRequest.java
  src/main/java/org/pingle/pingleserver/repository/MeetingRepository.java
  src/main/java/org/pingle/pingleserver/repository/PinRepository.java
  src/main/java/org/pingle/pingleserver/service/PinService.java
Labels: bug, fix

#89 [feat] 미팅 삭제 api 생성
  src/main/java/org/pingle/pingleserver/controller/MeetingController.java
  src/main/java/org/pingle/pingleserver/domain/Meeting.java
  src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
  src/main/java/org/pingle/pingleserver/repository/UserMeetingRepository.java
  src/main/java/org/pingle/pingleserver/service/MeetingService.java
Labels: api

#86 [feat] 마이핑글 참여 완료/예정 번개 리스트 api 생성
  src/main/java/org/pingle/pingleserver/controller/UserController.java
  src/main/java/org/pingle/pingleserver/dto/response/MyPingleResponse.java
  src/main/java/org/pingle/pingleserver/repository/MeetingRepository.java
  src/main/java/org/pingle/pingleserver/service/MeetingService.java
  src/main/java/org/pingle/pingleserver/service/PinService.java
  src/main/java/org/pingle/pingleserver/utils/TimeUtil.java
Labels: api

#90 [feat] 수정 pr입니다
  src/main/java/org/pingle/pingleserver/domain/Pin.java
  src/main/java/org/pingle/pingleserver/dto/reponse/PinResponse.java
  src/main/java/org/pingle/pingleserver/dto/response/MyPingleResponse.java
  src/main/java/org/pingle/pingleserver/service/PinService.java
Labels: bug

#92 [fix] get mypingle api 디데이 로직 변경
  src/main/java/org/pingle/pingleserver/dto/response/MyPingleResponse.java
Labels: api

#96 [feat] 서버 분리 (개발 서버, 프로덕션 서버) - first trial
  .github/workflows/dev-cd.yml
  .github/workflows/dev-ci.yml
  .github/workflows/prod-cd.yml
  .github/workflows/prod-ci.yml
  .gitignore
  Dockerfile-dev
  Dockerfile-prod
  src/main/java/org/pingle/pingleserver/controller/TestController.java
  src/main/resources/application.yml
Labels: db, config

#97 [feat] 서버 분리 (개발 서버, 프로덕션 서버) #95
  .github/workflows/dev-cd.yml
Labels: db, config

#98 [feat] 슬랙 알람 설정
  build.gradle
  src/main/java/org/pingle/pingleserver/exception/GlobalExceptionHandler.java
  src/main/java/org/pingle/pingleserver/service/AuthService.java
  src/main/java/org/pingle/pingleserver/service/MeetingService.java
  src/main/java/org/pingle/pingleserver/utils/SlackUtil.java
Labels: config

#106 [hotfix] 장소 검색 api 수정
  src/main/java/org/pingle/pingleserver/controller/OpenApiController.java
Labels: bug
